"""
Global relics package - relics available to all character classes.
Organized by rarity.
"""

# Import all global relics from rarity-based files
from .common import (
    Akabeko,
    Anchor,
    AncientTeaSet,
    BagOfPreparation,
    Vajra,
    # Additional Common Relics
    ArtOfWar,
    BagOfMarbles,
    BloodVial,
    BronzeScales,
    CentennialPuzzle,
    CeramicFish,
    DreamCatcher,
    HappyFlower,
    JuzuBracelet,
    Lantern,
    MawBank,
    MealTicket,
    Nunchaku,
    OddlySmoothStone,
    Omamori,
    Orichalcum,
    PenNib,
    PotionBelt,
    PreservedInsect,
    RegalPillow,
    SmilingMask,
    Strawberry,
    TheBoot,
    TinyChest,
    ToyOrnithopter,
    WarPaint,
    Whetstone
)

from .uncommon import (
    HornCleat,
    # Additional Uncommon Relics
    BlueCandle,
    BottledFlame,
    BottledLightning,
    BottledTornado,
    DarkstonePeriapt,
    EternalFeather,
    FrozenEgg,
    GremlinHorn,
    InkBottle,
    Kunai,
    LetterOpener,
    Matryoshka,
    MeatOnBone,
    MercuryHourglass,
    MoltenEgg,
    MummifiedHand,
    NinjaScroll,
    OrnamentalFan,
    Pantograph,
    PaperKrane,
    PaperPhrog,
    Pear,
    QuestionCard,
    SelfFormingClay,
    Shuriken,
    SingingBowl,
    StrikeDummy,
    Sundial,
    TheCourier,
    ToxicEgg,
    WhiteBeastStatue
)

from .rare import (
    BirdFacedUrn,
    # Additional Rare Relics
    Calipers,
    CaptainsWheel,
    DeadBranch,
    DuVuDoll,
    FossilizedHelix,
    Ginger,
    Girya,
    IceCream,
    LizardTail,
    Mango,
    OldCoin,
    PeacePipe,
    Pocketwatch,
    PrayerWheel,
    Shovel,
    StoneCalendar,
    TheSpecimen,
    ThreadAndNeedle,
    Tingsha,
    Torii,
    ToughBandages,
    TungstenRod,
    Turnip,
    UnceasingTop
)

from .boss import (
    SneckoEye,
    # Additional Boss Relics
    Astrolabe,
    BlackStar,
    BlackBlood,
    BustedCrown,
    CallingBell,
    CoffeeDripper,
    CursedKey,
    Ectoplasm,
    EmptyCage,
    FusionHammer,
    HoveringKite,
    MarkOfPain,
    PandorasBox,
    PhilosophersStone,
    RingOfSerpent,
    RunicCube,
    RunicDome,
    RunicPyramid,
    SacredBark,
    SlaversCollar,
    Sozu,
    TinyHouse,
    VelvetChoker,
    WristBlade
)

from .shop import (
    # Shop Relics
    Cauldron,
    ChemicalX,
    ClockworkSouvenir,
    DollysMirror,
    FrozenEye,
    HandDrill,
    LeesWaffle,
    MedicalKit,
    MembershipCard,
    PrismaticShard,
    Orrery,
    PotionBeltShop,
    SlingOfCourage,
    StrangeSpoonShop,
    TheAbacus,
    TwistedFunnel,
    Toolbox
)

from .event import (
    # Event Relics
    CultistHeadpiece,
    FaceOfCleric,
    GoldenIdol,
    BloodyIdol,
    GremlinVisage,
    MarkOfBloom,
    MutagenicStrength,
    Necronomicon,
    NilrysCodex,
    Enchiridion,
    NeowsLament,
    NlothHungryFace,
    OddMushroom,
    SsserpentHead,
    WarpedTongs,
    RedMask,
    NlothGift,
    SpiritPoop,
)

from .special import (
    # Special Relics
    RedKey,
    BlueKey,
    GreenKey
)

__all__ = [
    # Common (29)
    'Akabeko',
    'Anchor',
    'AncientTeaSet',
    'BagOfPreparation',
    'Vajra',
    'ArtOfWar',
    'BagOfMarbles',
    'BloodVial',
    'BronzeScales',
    'CentennialPuzzle',
    'CeramicFish',
    'DreamCatcher',
    'HappyFlower',
    'JuzuBracelet',
    'Lantern',
    'MawBank',
    'MealTicket',
    'Nunchaku',
    'OddlySmoothStone',
    'Omamori',
    'Orichalcum',
    'PenNib',
    'PotionBelt',
    'PreservedInsect',
    'RegalPillow',
    'SmilingMask',
    'Strawberry',
    'TheBoot',
    'TinyChest',
    'ToyOrnithopter',
    'WarPaint',
    'Whetstone',

    # Uncommon (22)
    'HornCleat',
    'BlueCandle',
    'BottledFlame',
    'BottledLightning',
    'BottledTornado',
    'DarkstonePeriapt',
    'EternalFeather',
    'FrozenEgg',
    'GremlinHorn',
    'InkBottle',
    'Kunai',
    'LetterOpener',
    'Matryoshka',
    'MeatOnBone',
    'MercuryHourglass',
    'MoltenEgg',
    'MummifiedHand',
    'NinjaScroll',
    'OrnamentalFan',
    'Pantograph',
    'PaperKrane',
    'PaperPhrog',
    'Pear',
    'QuestionCard',
    'SelfFormingClay',
    'Shuriken',
    'SingingBowl',
    'StrikeDummy',
    'Sundial',
    'TheCourier',
    'ToxicEgg',
    'WhiteBeastStatue',

    # Rare (21)
    'BirdFacedUrn',
    'Calipers',
    'CaptainsWheel',
    'DeadBranch',
    'DuVuDoll',
    'FossilizedHelix',
    'Ginger',
    'Girya',
    'IceCream',
    'LizardTail',
    'Mango',
    'OldCoin',
    'PeacePipe',
    'Pocketwatch',
    'PrayerWheel',
    'Shovel',
    'StoneCalendar',
    'TheSpecimen',
    'ThreadAndNeedle',
    'Tingsha',
    'Torii',
    'ToughBandages',
    'TungstenRod',
    'Turnip',
    'UnceasingTop',

    # Boss (20)
    'SneckoEye',
    'Astrolabe',
    'BlackStar',
    'BlackBlood',
    'BustedCrown',
    'CallingBell',
    'CoffeeDripper',
    'CursedKey',
    'Ectoplasm',
    'EmptyCage',
    'FusionHammer',
    'HoveringKite',
    'MarkOfPain',
    'PandorasBox',
    'PhilosophersStone',
    'RingOfSerpent',
    'RunicCube',
    'RunicDome',
    'RunicPyramid',
    'SacredBark',
    'SlaversCollar',
    'Sozu',
    'TinyHouse',
    'VelvetChoker',
    'WristBlade',

    # Shop (14)
    'Cauldron',
    'ChemicalX',
    'ClockworkSouvenir',
    'DollysMirror',
    'FrozenEye',
    'HandDrill',
    'LeesWaffle',
    'MedicalKit',
    'MembershipCard',
    'PrismaticShard',
    'Orrery',
    'PotionBeltShop',
    'SlingOfCourage',
    'StrangeSpoonShop',
    'TheAbacus',
    'TwistedFunnel',
    'Toolbox',

    # Event (14)
    'CultistHeadpiece',
    'FaceOfCleric',
    'GoldenIdol',
    'BloodyIdol',
    'GremlinVisage',
    'MarkOfBloom',
    'MutagenicStrength',
    'Necronomicon',
    'NilrysCodex',
    'Enchiridion',
    'NeowsLament',
    'NlothHungryFace',
    'OddMushroom',
    'SsserpentHead',
    'WarpedTongs',
    'RedMask',
    'NlothGift',
    'SpiritPoop',

    # Special (3)
    'RedKey',
    'BlueKey',
    'GreenKey',
]
