mode: debug # human | ai | debug
language: en
seed: 1
character: Ironclad
ascension: 0  # 0-20, 0 = no ascension
select_overflow: truncate # truncate | reselect
auto_select: False  # Auto select for all modes (human, ai, debug)

human:
  show_menu_option: False

ai:
  api_key: YOUR_API_KEY
  api_base: YOUR_MODEL_API_BASE
  model: YOUR_MODEL
  stream: True
  temperature: 0.7
  max_tokens: 8192
  timeout: 60

debug:
  print: False
  select_type: random
  god_mode: False  # If True, set all enemies to 1 HP at combat start
