mode: debug # human | ai | debug
language: en
seed: -1
character: Ironclad
selection_mode: "single"

human:
  auto_select: False
  show_menu_option: True

ai:
  # todo

debug:
  print: False
  select_type: random
  god_mode: False  # If True, apply 999 BufferPower at combat start