"""
Event 1 - Big Fish
"""
from events.base_event import Event
from actions.card import AddCardAction
from actions.display import SelectAction
from events.event_pool import register_event
from localization import LocalStr
from utils.types import CardType, RarityType

@register_event(
    event_id="big_fish",
    floors='early',
    weight=100
)
class BigFishEvent(Event):
    """Gain 3 random common cards"""
    
    def trigger(self) -> str:
        """Trigger the big fish blessing event"""
        # Display event description
        from actions.display import DisplayTextAction
        self.action_queue.add_action(DisplayTextAction(
            text_key="events.big_fish.description"
        ))
        
        # Build options
        options = []
        
        # Option 1: Receive 3 random common cards
        options.append(Option(
            name=LocalStr("events.big_fish.option1"),
            actions=[
                AddCardAction(pile="hand"),  # Will be generated by get_random_card in execute
                AddCardAction(pile="hand"),
                AddCardAction(pile="hand"),
            ]
        ))
        
        # Option 2: Receive 1 random uncommon card
        options.append(Option(
            name=LocalStr("events.big_fish.option2"),
            actions=[
                AddCardAction(pile="hand"),  # Will be generated by get_random_card
            ]
        ))
        
        # Option 3: Receive 3 random cards (mix of common and uncommon)
        for _ in range(3):
            options.append(Option(
                name=LocalStr("events.big_fish.option3", count=_+1),
                actions=[
                    AddCardAction(pile="hand"),
                ]
            ))
        
        # Display options and wait for selection
        self.action_queue.add_action(SelectAction(
            title=LocalStr("events.big_fish.title"),
            options=options
        ))
        
        return None
