"""
Relics package for Slay the Spire game.
Includes global relics (available to all characters) and character-specific relics.
"""

# Import global relics from all sub-modules
from .global_relics import (
    # Common (29)
    Akabeko,
    Anchor,
    AncientTeaSet,
    BagOfPreparation,
    Vajra,
    ArtOfWar,
    BagOfMarbles,
    BloodVial,
    BronzeScales,
    CentennialPuzzle,
    CeramicFish,
    DreamCatcher,
    HappyFlower,
    JuzuBracelet,
    Lantern,
    MawBank,
    MealTicket,
    Nunchaku,
    OddlySmoothStone,
    Omamori,
    Orichalcum,
    PenNib,
    PotionBelt,
    PreservedInsect,
    RegalPillow,
    SmilingMask,
    Strawberry,
    TheBoot,
    TinyChest,
    ToyOrnithopter,
    WarPaint,
    Whetstone,
    
    # Uncommon (22)
    HornCleat,
    BlueCandle,
    BottledFlame,
    BottledLightning,
    BottledTornado,
    DarkstonePeriapt,
    EternalFeather,
    FrozenEgg,
    GremlinHorn,
    InkBottle,
    Kunai,
    LetterOpener,
    Matryoshka,
    MeatOnBone,
    MercuryHourglass,
    MoltenEgg,
    MummifiedHand,
    NinjaScroll,
    OrnamentalFan,
    Pantograph,
    PaperKrane,
    PaperPhrog,
    Pear,
    QuestionCard,
    SelfFormingClay,
    Shuriken,
    SingingBowl,
    StrikeDummy,
    Sundial,
    TheCourier,
    ToxicEgg,
    WhiteBeastStatue,
    
    # Rare (21)
    BirdFacedUrn,
    Calipers,
    CaptainsWheel,
    DeadBranch,
    DuVuDoll,
    FossilizedHelix,
    Ginger,
    Girya,
    IceCream,
    LizardTail,
    Mango,
    OldCoin,
    PeacePipe,
    Pocketwatch,
    PrayerWheel,
    Shovel,
    StoneCalendar,
    TheSpecimen,
    ThreadAndNeedle,
    Tingsha,
    Torii,
    ToughBandages,
    TungstenRod,
    Turnip,
    UnceasingTop,
    
    # Boss (18)
    SneckoEye,
    Astrolabe,
    BlackStar,
    BustedCrown,
    CallingBell,
    CoffeeDripper,
    CursedKey,
    Ectoplasm,
    EmptyCage,
    FusionHammer,
    HoveringKite,
    MarkOfPain,
    PandorasBox,
    PhilosophersStone,
    RingOfSerpent,
    RunicDome,
    RunicPyramid,
    SacredBark,
    SlaversCollar,
    Sozu,
    TinyHouse,
    VelvetChoker,
    WristBlade,
    
    # Shop (14)
    Cauldron,
    ChemicalX,
    ClockworkSouvenir,
    DollysMirror,
    FrozenEye,
    HandDrill,
    LeesWaffle,
    MedicalKit,
    MembershipCard,
    PrismaticShard,
    Orrery,
    PotionBeltShop,
    SlingOfCourage,
    StrangeSpoonShop,
    TheAbacus,
    TwistedFunnel,
    Toolbox,
    
    # Event (14)
    CultistHeadpiece,
    FaceOfCleric,
    GoldenIdol,
    BloodyIdol,
    GremlinVisage,
    MarkOfBloom,
    MutagenicStrength,
    Necronomicon,
    NilrysCodex,
    Enchiridion,
    NeowsLament,
    NlothHungryFace,
    OddMushroom,
    WarpedTongs,
    RedMask,
    NlothGift,
    SpiritPoop,
    
    # Special (3)
    RedKey,
    BlueKey,
    GreenKey,
)

# Import Ironclad-specific relics
from .character.ironclad import (
    BurningBlood,
    RedSkull,
    ChampionBelt,
    CharonsAshes,
    MagicFlower,
    BlackBlood,
    Runicube,
    BrimStone,
    OrangePellets,
)

__all__ = [
    # Global Common (29)
    'Akabeko',
    'Anchor',
    'AncientTeaSet',
    'BagOfPreparation',
    'Vajra',
    'ArtOfWar',
    'BagOfMarbles',
    'BloodVial',
    'BronzeScales',
    'CentennialPuzzle',
    'CeramicFish',
    'DreamCatcher',
    'HappyFlower',
    'JuzuBracelet',
    'Lantern',
    'MawBank',
    'MealTicket',
    'Nunchaku',
    'OddlySmoothStone',
    'Omamori',
    'Orichalcum',
    'PenNib',
    'PotionBelt',
    'PreservedInsect',
    'RegalPillow',
    'SmilingMask',
    'Strawberry',
    'TheBoot',
    'TinyChest',
    'ToyOrnithopter',
    'WarPaint',
    'Whetstone',
    
    # Global Uncommon (22)
    'HornCleat',
    'BlueCandle',
    'BottledFlame',
    'BottledLightning',
    'BottledTornado',
    'DarkstonePeriapt',
    'EternalFeather',
    'FrozenEgg',
    'GremlinHorn',
    'InkBottle',
    'Kunai',
    'LetterOpener',
    'Matryoshka',
    'MeatOnBone',
    'MercuryHourglass',
    'MoltenEgg',
    'MummifiedHand',
    'NinjaScroll',
    'OrnamentalFan',
    'Pantograph',
    'PaperKrane',
    'PaperPhrog',
    'Pear',
    'QuestionCard',
    'SelfFormingClay',
    'Shuriken',
    'SingingBowl',
    'StrikeDummy',
    'Sundial',
    'TheCourier',
    'ToxicEgg',
    'WhiteBeastStatue',
    
    # Global Rare (21)
    'BirdFacedUrn',
    'Calipers',
    'CaptainsWheel',
    'DeadBranch',
    'DuVuDoll',
    'FossilizedHelix',
    'Ginger',
    'Girya',
    'IceCream',
    'LizardTail',
    'Mango',
    'OldCoin',
    'PeacePipe',
    'Pocketwatch',
    'PrayerWheel',
    'Shovel',
    'StoneCalendar',
    'TheSpecimen',
    'ThreadAndNeedle',
    'Tingsha',
    'Torii',
    'ToughBandages',
    'TungstenRod',
    'Turnip',
    'UnceasingTop',
    
    # Global Boss (18)
    'SneckoEye',
    'Astrolabe',
    'BlackStar',
    'BustedCrown',
    'CallingBell',
    'CoffeeDripper',
    'CursedKey',
    'Ectoplasm',
    'EmptyCage',
    'FusionHammer',
    'HoveringKite',
    'MarkOfPain',
    'PandorasBox',
    'PhilosophersStone',
    'RingOfSerpent',
    'RunicDome',
    'RunicPyramid',
    'SacredBark',
    'SlaversCollar',
    'Sozu',
    'TinyHouse',
    'VelvetChoker',
    'WristBlade',
    
    # Global Shop (14)
    'Cauldron',
    'ChemicalX',
    'ClockworkSouvenir',
    'DollysMirror',
    'FrozenEye',
    'HandDrill',
    'LeesWaffle',
    'MedicalKit',
    'MembershipCard',
    'PrismaticShard',
    'Orrery',
    'PotionBeltShop',
    'SlingOfCourage',
    'StrangeSpoonShop',
    'TheAbacus',
    'TwistedFunnel',
    'Toolbox',
    
    # Global Event (14)
    'CultistHeadpiece',
    'FaceOfCleric',
    'GoldenIdol',
    'BloodyIdol',
    'GremlinVisage',
    'MarkOfBloom',
    'MutagenicStrength',
    'Necronomicon',
    'NilrysCodex',
    'Enchiridion',
    'NeowsLament',
    'NlothHungryFace',
    'OddMushroom',
    'WarpedTongs',
    'RedMask',
    'NlothGift',
    'SpiritPoop',
    
    # Global Special (3)
    'RedKey',
    'BlueKey',
    'GreenKey',
    
    # Ironclad-specific (8)
    'BurningBlood',
    'RedSkull',
    'ChampionBelt',
    'CharonsAshes',
    'MagicFlower',
    'BlackBlood',
    'Runicube',
    'BrimStone',
    'OrangePellets',
]
